export const USER_REGISTRATION_SUBMIT = 'USER_REGISTRATION_SUBMIT';
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAIL_PASSWORD = 'USER_REGISTRATION_FAIL_PASSWORD';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_FAILS = 'FETCH_ARTICLES';
