export const USER_REGISTRATION_SUBMIT = 'USER_REGISTRATION_SUBMIT';
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAIL_PASSWORD = 'USER_REGISTRATION_FAIL_PASSWORD';
